module.exports = [
  {
    id: 1,
    slug: "vip-transportation",
    img: "/img/blog/1.png",
    title: "V.I.P Transportation",
    date: "Jan 06, 2023",
    description: "We can provide any transportation by land, by sea and by air. Upon your request your transfers can be arranged by car, limousine, minibus, helicopter, sea plane or private air plane",
    delayAnimation: "100",
    details: `For decades, travelers have been escaping to the Catskills — a mountainous region in upstate New York — whenever they’ve needed a reset.`,
    tag: "art",
  },
  {
    id: 2,
    slug: "berth-reservations",
    img: "/img/blog/2.png",
    title: "Berth Reservations",
    date: "Jan 06, 2023",
    description: "Due to over-requirements for berths during the high season in Turkey, marinas become insufficient and it is difficult to find moorings.",
    delayAnimation: "200",
    details: `For decades, travelers have been escaping to the Catskills — a mountainous region in upstate New York — whenever they’ve needed a reset.`,
    tag: "beaches",
  },
  {
    id: 3,
    slug: "land-excursion",
    img: "/img/blog/3.png",
    title: "Land Excursion",
    date: "Jan 06, 2023",
    description: "Due to the abundance of excursion alternatives along the Turkish Coast we offer our guests an abundance of highly detailed and unique itineraries.",
    delayAnimation: "300",
    details: `For decades, travelers have been escaping to the Catskills — a mountainous region in upstate New York — whenever they’ve needed a reset.`,
    tag: "adventure",
  },
  {
    id: 4,
    slug: "travel-and-accommodation",
    img: "/img/blog/4.png",
    title: "Travel and Accommodation",
    date: "Jan 06, 2023",
    description: "Our staff is experienced in making the arrangements for hotel reservations for overnight tours.",
    delayAnimation: "400",
    details: `For decades, travelers have been escaping to the Catskills — a mountainous region in upstate New York — whenever they’ve needed a reset.`,
    tag: "explore",
  },
  {
    id: 5,
    slug: "clearance",
    img: "/img/blog/5.png",
    title: "Clearance",
    date: "Jan 06, 2023",
    description: "To avoid any restrictions or inconveniences during your cruise in Turkey, we handle all clearance",
    delayAnimation: "100",
    details: `For decades, travelers have been escaping to the Catskills — a mountainous region in upstate New York — whenever they’ve needed a reset.`,
    tag: "holidays",
  },
  {
    id: 6,
    slug: "travel-and-accommodation",
    img: "/img/blog/6.png",
    title: "Travel and Accommodation",
    date: "Jan 06, 2023",
    description: "Our staff is experienced in making the arrangements for hotel reservations for overnight tours.",
    delayAnimation: "200",
    details: `For decades, travelers have been escaping to the Catskills — a mountainous region in upstate New York — whenever they’ve needed a reset.`,
    tag: "travel",
  }
];
